# opcional, autogenerado
version: "3.8"

services:
  mysql-service:
    image: mysql:8
    container_name: mysqlserver
    #env_file:
    #- ".env.dev"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - bdds-net
    volumes:
      - vol-bdd-mysql:/var/lib/mysql
  
  postgres-service:
    image: postgres:15-alpine
    container_name: postgresdb
    #env_file:
    #  - ".env.dev"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - bdds-net
    volumes:
      - vol-bdd-postgres:/var/lib/postgresql/data
  
  mongo-service:
    image: mongo:6
    container_name: mongodb
    #env_file:
    #  - ".env.dev"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - bdds-net
    volumes:
      - vol-bdd-mongo:/data/db

networks:
  bdds-net:
    name: bdds-net

volumes:
  vol-bdd-mysql:
    name: vol-bdd-mysql
  vol-bdd-postgres:
    name: vol-bdd-postgres
  vol-bdd-mongo:
    name: vol-bdd-mongo