# opcional, autogenerado
version: "3.8"

services:
  mysql-service:
    image: mysql:8
    container_name: mysqlserver
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_dev_root_pass
      MYSQL_USER_FILE: /run/secrets/mysql_dev_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_dev_pass
      MYSQL_DATABASE_FILE: /run/secrets/mysql_dev_db
    secrets:
      - mysql_dev_root_pass
      - mysql_dev_user
      - mysql_dev_pass
      - mysql_dev_db
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - bdds-net
    volumes:
      - vol-bdd-mysql:/var/lib/mysql
    healthcheck:
      # test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD}"]
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u ${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
  
  postgres-service:
    image: postgres:15-alpine
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_dev_pass
      POSTGRES_USER_FILE: /run/secrets/postgres_dev_user
      POSTGRES_DB_FILE: /run/secrets/postgres_dev_db
    secrets:
      - postgres_dev_pass
      - postgres_dev_user
      - postgres_dev_db
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - bdds-net
    volumes:
      - vol-bdd-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  
  mongo-service:
    image: mongo:6
    container_name: mongodb
    secrets:
      - mongo_dev_user
      - mongo_dev_pass
      - mongo_dev_db
    command: >
      sh -c "
        export MONGO_INITDB_ROOT_USERNAME=$(cat /run/secrets/mongo_dev_user) &&
        export MONGO_INITDB_ROOT_PASSWORD=$(cat /run/secrets/mongo_dev_pass) &&
        export MONGO_INITDB_DATABASE=$(cat /run/secrets/mongo_dev_db) &&
        exec docker-entrypoint.sh mongod
      "
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - bdds-net
    volumes:
      - vol-bdd-mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  
  app-backend:
    image: node:18-alpine
    container_name: backend-app-node
    working_dir: /app
    volumes:
      - ./:/app
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    networks:
      - bdds-net
    depends_on:
      mysql-service:
        condition: service_healthy
      postgres-service:
        condition: service_healthy
      mongo-service:
        condition: service_healthy
    
networks:
  bdds-net:
    name: bdds-net

volumes:
  vol-bdd-mysql:
    name: vol-bdd-mysql
  vol-bdd-postgres:
    name: vol-bdd-postgres
  vol-bdd-mongo:
    name: vol-bdd-mongo

secrets:
  mysql_dev_root_pass:
    file: ./secrets/mysql/mysql_dev_root_pass.txt
  mysql_dev_user:
    file: ./secrets/mysql/mysql_dev_user.txt
  mysql_dev_pass:
    file: ./secrets/mysql/mysql_dev_pass.txt
  mysql_dev_db:
    file: ./secrets/mysql/mysql_dev_db.txt
  
  postgres_dev_user:
    file: ./secrets/postgres/postgres_dev_user.txt
  postgres_dev_pass:
    file: ./secrets/postgres/postgres_dev_pass.txt
  postgres_dev_db:
    file: ./secrets/postgres/postgres_dev_db.txt

  mongo_dev_user:
    file: ./secrets/mongo/mongo_dev_user.txt
  mongo_dev_pass:
    file: ./secrets/mongo/mongo_dev_pass.txt
  mongo_dev_db:
    file: ./secrets/mongo/mongo_dev_db.txt