# opcional, autogenerado
version: "3.8"

services:
  mysql-service:
    image: mysql:8
    container_name: mysqlserver
    env_file:
      - ".env.dev"
      #- MYSQL_ROOT_PASSWORD=12345
      #- MYSQL_USER=user
      #- MYSQL_PASSWORD=1234
      #- MYSQL_DATABASE=sqldb
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - bdds-net
    volumes:
      - vol-bdd-mysql:/var/lib/mysql
  
  postgres-service:
    image: postgres:15-alpine
    container_name: postgresdb
    env_file:
      - ".env.dev"
    #environment:
      #- POSTGRES_PASSWORD=12345
      #- POSTGRES_USER=user
      #- POSTGRES_DB=bddpostgres
    #env_file:
    #  - ".env"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - bdds-net
    volumes:
      - vol-bdd-postgres:/var/lib/postgresql/data
  
  mongo-service:
    image: mongo:6
    container_name: mongodb
    env_file:
      - ".env.dev"
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=user
    #  - MONGO_INITDB_ROOT_PASSWORD=12345
    #  - MONGO_INITDB_DATABASE=bddmongo
    #env_file:
    #  - ".env"
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - bdds-net
    volumes:
      - vol-bdd-mongo:/data/db

networks:
  bdds-net:
    name: bdds-net

volumes:
  vol-bdd-mysql:
    name: vol-bdd-mysql
  vol-bdd-postgres:
    name: vol-bdd-postgres
  vol-bdd-mongo:
    name: vol-bdd-mongo